### ISSUE TITLE
requirement python-igraph cannot be installed automatically

### ISSUE THREAD

**Issue by gundramleifert** [LiquidFun/Airway#1]
` pip install -r requirements.txt` and `pip install python-igraph` fails.
tested with `pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)` and `pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)` on ubuntu 18.04

**Comment by LiquidFun** [comment]
You can install python-igraph with apt: `apt install python3-igraph`. I can't install it pip either. I'll remove it as a pip dependency and add it as an optional installation with a package-manager. Thanks.

**Comment by gundramleifert** [comment]
That worked Thanks
