### ISSUE TITLE
question about classifiction.yaml

### ISSUE THREAD

**Issue by DonnyLiu7** [LiquidFun/Airway#19]
Normally, the trachea directly branches into the Left Bronchus (LB) and Right Bronchus (RB). Why is the trachea's 'children' in the YAML configuration set to 'bronchus' before specifying LB and RB? If there is no 'brochus' in the bronchi, how would the code behave?

**Comment by LiquidFun** [comment]
Anatomically yes, you are right. This is mostly an implementation detail in the project. The trachea has two points, one at the top of the model and one where the split occurs. I simply named the upper one `trachea` and the lower one `bronchus`

![image](https://github.com/LiquidFun/Airway/assets/8319560/e6c2067a-97ed-49c3-9f22-503252fdd525)

If you remove the `bronchus` node then it will work as long as you add `LB` and `RB` as children for `trachea`. Or alternatively remove only `trachea`, although I'm not entirely sure if that works immediately.
