### ISSUE TITLE
Demo for dicom?

### ISSUE THREAD

**Issue by lancexiang** [LiquidFun/Airway#3]
I don't know how to generate the data structure as described in your readme, since i only have the lung HRCT. Is there any demo for generate the data structure as yours from the original dicom?

**Comment by LiquidFun** [comment]
The initial structure was created using Synapse3D by a surgeon. Unfortunately that software is not open source and I currently do not know of good alternatives. The masks contained essentially the same data as the raw dicom data, but all non-bronchus voxels had been set to -1000. 

We are currently working to eliminate this step as well using deep learning, although it's not quite there yet.

If you have the masks then you can use the script in `scripts/separate-bronchus-data.sh`.   

I'll extend the README, as this isn't mentioned there, thanks!

**Comment by LiquidFun** [comment]
There is now a tutorial which explains a lot more about how to run and use the cli. Can be ran with `airway tutorial`.
