### ISSUE TITLE
RAW & DICOM 

### ISSUE THREAD

**Issue by Gweiqi** [LiquidFun/Airway#4]
dear developer,
This is an outstanding work. I am trying to simulate aerosol deposition in human lungs on a computer  Your work are very helpful to my current research.Whether this program can be used to segment the lung airway from. RAW or DICOM files?
Sincerely, yours

**Comment by LiquidFun** [comment]
Thanks! Unfortunately currently you need a bronchus mask, i.e. a DICOM image where only the bronchus is annotated, and everything else is empty. We had a surgeon do it with software called Synapse 3D. There might be alternatives, you just need a good bronchus voxel model. 

If you have that then everything else can be made using this software.

**Comment by Gweiqi** [comment]
Thank you very much for your reply.If I succeed, I will cite your work where necessary.Do you have any published articles about this work？

**Comment by LiquidFun** [comment]
Happy to help and thanks for the interest! Not yet as I'm still working on this. The plan is to publish something in the next 2-3 months though. If you want to cite it before then I guess you can use the repository for now.

Many parts aren't finalized yet, so there is no proper documentation yet. Let me know if you need guidance on getting it to work.

**Comment by pkglimmer** [comment]
Hi Brutenis,

Great job and thank you so much for sharing!! just two questions:

1. As you have mentioned above, the input has to be some specific format of annotation made by professionals. Although I have some segmented airway masks in NIFTI format, I still don't quite understand how to organize the data structure (maybe some hint on how to use separate-bronchus-files.sh)

2. I am currently working on a project about airway segmentation using 3d unet deep learning models. For possible future steps, we could build an end-to-end (chest CT to airway tree) tool combining your work and segmentation network. If you are interested in using those DL models, maybe we could work together.

**Comment by LiquidFun** [comment]
Hey Peikun,

Ah, yes, thanks for reminding me. I have updated the README, especially the data section. Let me know if it helps. Considering you have NIFTI images, the easiest will probably be to export them as 3-dimensional numpy arrays for stage-01 (as described in the README).

A collaboration would be cool if this project works well for your data as well. Let me know what results you get. Is your code open source?

**Comment by pkglimmer** [comment]
> > Hi Brutenis,
> > Great job and thank you so much for sharing!! just two questions:
> > 
> > 1. As you have mentioned above, the input has to be some specific format of annotation made by professionals. Although I have some segmented airway masks in NIFTI format, I still don't quite understand how to organize the data structure (maybe some hint on how to use separate-bronchus-files.sh)
> > 2. I am currently working on a project about airway segmentation using 3d unet deep learning models. For possible future steps, we could build an end-to-end (chest CT to airway tree) tool combining your work and segmentation network. If you are interested in using those DL models, maybe we could work together.
> 
> Hey Peikun,
> 
> Ah, yes, thanks for reminding me. I have updated the README, especially the data section. Let me know if it helps. Considering you have NIFTI images, the easiest will probably be to export them as 3-dimensional numpy arrays for stage-01 (as described in the README).
> 
> A collaboration would be cool if this project works well for your data as well. Let me know what results you get. Is your code open source?

Thanks for your quick response! I have looked at README you updated. It explains a lot, and the first processing stage feels clear to me now. I have just started developing the 3d segmentation algorithm and will definitely make it open source. 
Best, 
Peikun

**Comment by LiquidFun** [comment]
Great to hear! Excited to see your results then! Let me know how it goes.
